name: money_management
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^4.2.1
  retrofit: ^4.1.0
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  sqflite: ^2.3.2
  path: ^1.9.0
  logger: ^2.1.0
  collection: ^1.18.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  go_router: ^13.2.1
  lottie: ^3.1.0
  flutter_svg: ^2.0.10+1
  custom_sliding_segmented_control: ^1.8.1
  intl: ^0.19.0
  archive: 3.4.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  retrofit_generator: ^8.1.0
  flutter_gen_runner: ^5.4.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/app_icon/launcher_app_icon.png
    - assets/lotties/input_complete.json

flutter_gen:
  output: lib/constants/resources/gen/
  integrations:
    flutter_svg: true
  colors:
    inputs:
      - assets/colors/colors.xml

flutter_icons:
  android: true
  adaptive_icon_foreground: "assets/app_icon/launcher_app_icon.png"
  adaptive_icon_background: "#233BA4"
  ios: true
  image_path: "assets/app_icon/launcher_app_icon.png"
